// Generated by `supabase gen types typescript`, against the live schema on
// 2026-09-10 with migrations 0001 through 0006 applied.
//
// It replaces a copy that had been hand-patched twice — `pets.sex` and
// `pets.activity_level` made nullable for 0003 and 0004, and the three tables
// of 0006 written out by hand. The regeneration confirmed every one of those
// patches and corrected exactly one thing: `pets.Insert.sex` is **optional**,
// not required. Nothing was broken by it, because pet creation goes through
// the `create_pet_with_owner` RPC rather than a direct insert — which is also
// why nobody noticed.
//
// Regenerate rather than patch:
//
//   npx supabase gen types typescript --project-id <ref> > lib/database.types.ts
//   npx prettier --write lib/database.types.ts
//
// It reads the *live* schema, so it only tells the truth about a project the
// pending migrations have actually been applied to.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      pet_events: {
        Row: {
          created_at: string;
          created_by: string | null;
          details: Json;
          duration_minutes: number | null;
          id: string;
          kind: string;
          note: string | null;
          occurred_at: string;
          pet_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          details?: Json;
          duration_minutes?: number | null;
          id?: string;
          kind: string;
          note?: string | null;
          occurred_at?: string;
          pet_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          details?: Json;
          duration_minutes?: number | null;
          id?: string;
          kind?: string;
          note?: string | null;
          occurred_at?: string;
          pet_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pet_events_pet_id_fkey";
            columns: ["pet_id"];
            isOneToOne: false;
            referencedRelation: "pets";
            referencedColumns: ["id"];
          },
        ];
      };
      pet_owners: {
        Row: {
          joined_at: string;
          pet_id: string;
          role: string;
          user_id: string;
        };
        Insert: {
          joined_at?: string;
          pet_id: string;
          role?: string;
          user_id: string;
        };
        Update: {
          joined_at?: string;
          pet_id?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pet_owners_pet_id_fkey";
            columns: ["pet_id"];
            isOneToOne: false;
            referencedRelation: "pets";
            referencedColumns: ["id"];
          },
        ];
      };
      pet_treatments: {
        Row: {
          administered_on: string;
          created_at: string;
          created_by: string | null;
          id: string;
          kind: string;
          name: string | null;
          next_due_on: string | null;
          note: string | null;
          pet_id: string;
          updated_at: string;
        };
        Insert: {
          administered_on: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          kind: string;
          name?: string | null;
          next_due_on?: string | null;
          note?: string | null;
          pet_id: string;
          updated_at?: string;
        };
        Update: {
          administered_on?: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          kind?: string;
          name?: string | null;
          next_due_on?: string | null;
          note?: string | null;
          pet_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pet_treatments_pet_id_fkey";
            columns: ["pet_id"];
            isOneToOne: false;
            referencedRelation: "pets";
            referencedColumns: ["id"];
          },
        ];
      };
      pet_weights: {
        Row: {
          created_at: string;
          created_by: string | null;
          grams: number;
          id: string;
          measured_on: string;
          note: string | null;
          pet_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          grams: number;
          id?: string;
          measured_on: string;
          note?: string | null;
          pet_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          grams?: number;
          id?: string;
          measured_on?: string;
          note?: string | null;
          pet_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pet_weights_pet_id_fkey";
            columns: ["pet_id"];
            isOneToOne: false;
            referencedRelation: "pets";
            referencedColumns: ["id"];
          },
        ];
      };
      pets: {
        Row: {
          activity_level: string | null;
          birth_date: string | null;
          birth_date_approximate: boolean;
          breed_primary: string | null;
          breed_secondary: string | null;
          created_at: string;
          exercise_goal_minutes: number | null;
          id: string;
          is_mixed: boolean;
          name: string;
          photo_url: string | null;
          sex: string | null;
          spayed_neutered: boolean | null;
          species: string;
          updated_at: string;
          vet_emergency: Json | null;
          vet_primary: Json | null;
        };
        Insert: {
          activity_level?: string | null;
          birth_date?: string | null;
          birth_date_approximate?: boolean;
          breed_primary?: string | null;
          breed_secondary?: string | null;
          created_at?: string;
          exercise_goal_minutes?: number | null;
          id?: string;
          is_mixed?: boolean;
          name: string;
          photo_url?: string | null;
          sex?: string | null;
          spayed_neutered?: boolean | null;
          species?: string;
          updated_at?: string;
          vet_emergency?: Json | null;
          vet_primary?: Json | null;
        };
        Update: {
          activity_level?: string | null;
          birth_date?: string | null;
          birth_date_approximate?: boolean;
          breed_primary?: string | null;
          breed_secondary?: string | null;
          created_at?: string;
          exercise_goal_minutes?: number | null;
          id?: string;
          is_mixed?: boolean;
          name?: string;
          photo_url?: string | null;
          sex?: string | null;
          spayed_neutered?: boolean | null;
          species?: string;
          updated_at?: string;
          vet_emergency?: Json | null;
          vet_primary?: Json | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          display_name: string | null;
          id: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          id: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      create_pet_with_owner: {
        Args: { pet: Json };
        Returns: {
          activity_level: string | null;
          birth_date: string | null;
          birth_date_approximate: boolean;
          breed_primary: string | null;
          breed_secondary: string | null;
          created_at: string;
          exercise_goal_minutes: number | null;
          id: string;
          is_mixed: boolean;
          name: string;
          photo_url: string | null;
          sex: string | null;
          spayed_neutered: boolean | null;
          species: string;
          updated_at: string;
          vet_emergency: Json | null;
          vet_primary: Json | null;
        };
        SetofOptions: {
          from: "*";
          to: "pets";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      is_pet_owner: { Args: { p_pet_id: string }; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
